### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by hugosmie** [cortex-lab/phy#1245]
![indexError](https://github.com/cortex-lab/phy/assets/74908710/59e1dc4f-fa0d-4b2f-a3ed-53a1bdbd1365)
I encountered this issue when I split the cluster in the feature space with ctl+left click. And after this error, the following operation would raise this issue again and again (like simply select a cluster and so on).
It didn't fix even after I reinstall the phy.

**Comment by hugosmie** [comment]
![image](https://github.com/cortex-lab/phy/assets/74908710/4c6ac34f-ece0-4ce5-8246-99506dc31b73)

**Comment by zm711** [comment]
Could you post how you installed phy?

**Comment by zm711** [comment]
Yeah different packages update different so that can lead to the problems. I've actually had more success just installing with the yaml file. Could you download:

`environment.yml` then edit it to limit python to 3.11 (ie python=3.11, I have PR to fix the 3.12 issue, but it is not merged yet). Try that and let me know how that goes.

**Comment by zm711** [comment]
Closing for lack of response. Feel free to reopen if you try the suggestion and it doesn't work.

Note that you will need to edit numpy < 2.0 since we have not tested on 2.0.
