### ISSUE TITLE
ImportError: DLL load failed while importing _imaging

### ISSUE THREAD

**Issue by H-Jiyoung** [cortex-lab/phy#1294]
Hi all, 

Recently, I tried to reinstall phy2, but I cannot execute GUI because of 'Import Error'.
How can I solve this problem...?
The attached picture shows the error message. 

I originally installed phy2 successfully even though the installed Python version was 3.12. 
However, I had the same issues as #1290 and I found some comments that this would be because of the Python version.
So, I reinstalled Python version 3.11 and phy. But this time, phy2 was not executed at all with the 'Import error' as below.
I want to solve this problem...
Thank you in advance.

Python ver. = 3.11.9
![error message](https://github.com/cortex-lab/phy/assets/172590762/9e642a51-52b1-437d-9817-08b90c3908fb)

**Comment by zm711** [comment]
Could you do me a favor and translate the last bit of Korean. It says `ImportError: DLL load failed while importing _imaging:...`

I just want to make sure that's not important info.

Second, how did you install phy?

**Comment by H-Jiyoung** [comment]
Hi,
Thank you for your reply.
I strictly followed all instructions in the installation part of phy GitHub. The Korean part means "The specified module was not found". Fortunately, I solved the "Import Error" by typing `pip install -U Pillow` but there is still the same issue as #1290. Is there any method to open 'TemplateFeature View'?
The error message is attached below.

![image](https://github.com/cortex-lab/phy/assets/172590762/cd08f676-85a3-46d5-a948-89cc3d177bdb)

**Comment by zm711** [comment]
Sorry for the delay. Great that you got your immediate issue fixed. Which KS are you using. Or are you using Spikeinterface. If you are using KS3 they didn't fully implement phy functionality. So you could do

```
phy extract-waveforms params.py
```

but this causes a "frozen" state so a lot of people complain about using this. If you go to do a split often the numbers aren't what people expect because this only takes a subsample rather than the real data so it is prone to some pretty wild sampling biases. But if using KS3 it is the only way you can use some version of the feature view.

SpikeInterface has an export_to_phy that can provide most of the phy views even with KS3 sorted data.

**Comment by zm711** [comment]
I'm going to close this for lack of responses. Just open a new issue if something else comes up.
