### ISSUE TITLE
TimeSeries and Epochs data structures

### ISSUE THREAD

**Issue by rossant** [cortex-lab/phy#689]
These classes will allow us to manipulate time-dependent data such as spike trains, continuous-time signals, epochs, and so on.
## TimeSeries

Represent a discrete `time => data` function, where `data` has 0, 1, or N values. An `X` instance has the following properties:
- `X.time`: a `(n_times,)` array, in seconds
- `X.data`: a `(n_times, n_dims)` array

Operations (some ideas):
- `X + something`: operates on `X.data`
- `X[ind]`: operates on `X.data`
- `X[X.time > t0]`: subselect the time series
- `X.between(t0, t1)`, `X.after(t0)`, etc.: subselect
- `X.resample(2.)`: down-sampling or up-sampling (with interpolation?)
## Epochs

Represent a list of epochs, with possibly some data associated to each epoch.

Properties:
- `X.start`: a `(n_times,)` array
- `X.stop`: a `(n_times,)` array
- `X.data`: a `(n_times, n_dims)` array

Operations:
- `X + something`
- `X.start_after(t0)`, `X.end_before(t1)`, etc.

cc @nsteinme and @apeyrache

**Comment by nsteinme** [comment]
I haven't researched all the options available, but rather than implementing things from scratch it may be wise to simply make use of existing electrophysiology analysis toolboxes in python for this sort of thing. One I know if is elephant: http://elephant.readthedocs.org/en/latest/index.html. For that one at least, it is open source so if something about it is not meeting your needs it could be implemented there, I suppose. 

The real question is the data format that the user will supply these things as?
