### ISSUE TITLE
Trace and waveform filtering

### ISSUE THREAD

**Issue by rossant** [cortex-lab/phy#889]
Support multiple types of time filtering in traces, that would also affect extracted waveforms (in the waveform view) and raw amplitudes in the amplitude view.

@marius10p could you give more information about what filters exactly you would like and how they should be computed (with mathematical formulas or pseudocode)?

**Comment by marius10p** [comment]
I like the idea of this affecting the extracted waveforms! Would this option be switchable quickly? Sometimes we want to see the raw data waveforms because filtering can change their shape in funny ways. Switching back and forth to see the change in shape from filtering would be valuable. 

In Kilosort2, we do the following by default:

1) median subtraction across all channels
2) high-pass filtering at 150Hz using a 3-node butterworth filter. The matlab formula is:

[b1, a1] = butter(3, ops.fshigh/ops.fs*2, 'high');
datr = filter(b1, a1, dataRAW);
datr = flipud(datr);
datr = filter(b1, a1, datr);
datr = flipud(datr); 

This is done to avoid Matlab's filtfilt function, which requires double inputs and so will be slow on most GPUs. The compromise is to use a butterworth filter with very few nodes (3).

**Comment by rossant** [comment]
Done! I added [a plugin example in the documentation](https://phy.readthedocs.io/en/latest/plugins/#adding-a-custom-raw-data-filter).

**Comment by 410pfeliciano** [comment]
Hello all,

I remembered switching from raw to filter data in the trace view, but I forgot the shortcut to do that. Alt+R is not working on my desktop.  Is there any other shortcut?

**Comment by rossant** [comment]
You should find the action in the view menu
