### ISSUE TITLE
phy GUI has invisible parts

### ISSUE THREAD

**Issue by HunsonAbadeer1** [cortex-lab/phy#987]
I am trying to vie my kilosort data in the phy GUI, but only the ClusterView and the SimilarityView contain anything. The ClusterScatterView seems o contain invisible information, if I click on it randomly it changes the ClusterView and the SimilarityView. Does anyone have an idea how to solve this.
![76438161-ed07ce00-63ba-11ea-8014-0de025e34c62](https://user-images.githubusercontent.com/62069556/77903386-12ce1780-7283-11ea-9e30-daf76656a3ec.PNG)
There are no error messages when I start it with the anaconda prompt. I tried it with the clear state as well, that didn´t change anything. The Graphics Card is an NVIDIA GeForce RTX 2080 Ti, the driver version is 26.21.14.4166.
With the debug command I get a lot of these:
![76532109-6fa19380-6476-11ea-9e53-4d5714d835cf](https://user-images.githubusercontent.com/62069556/77903485-3b561180-7283-11ea-9a71-ae1bc16fb4f9.PNG)
Any idea how to fix this?

**Comment by chouran** [comment]
I got the exact same errors with SpyKing Circus data. Did you manage to fix it ?

**Comment by HunsonAbadeer1** [comment]
Nope, so far not. I have also written to other people with the same problem and there is so far no solution.

**Comment by rossant** [comment]
Is this Windows? It might be that the Python process is using, for some reason, the native OpenGL 1.x driver (which is extremely old) rather than the NVIDIA driver. I'll try to see if I can reproduce the issue on my Windows computer.

**Comment by HunsonAbadeer1** [comment]
Yes, this is Windows.

**Comment by chouran** [comment]
If it might help, there is a problem with the windows PyOpenGL package, apparently, some files are missing. I have follow this [tutorial](https://codeyarns.com/2012/04/27/pyopengl-installation-notes-for-windows/ ) and download and install the unofficial package supposed to fix those bug (from [here](https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyopeng). However there is now a problem with the pyrender package which is said not to be compatible with this new version of PyOpenGL. It might provide some insight

**Comment by rossant** [comment]
Thanks that's helpful!
Otherwise just "pip install pyopengl" is not working on Windows?

**Comment by RynzzZ** [comment]
Hi all, 

I'm currently having the same probelms. But I'm connecting to lab PC thru remote desktop due to current intense COVID-19 situation. For me, this Phy GUI having invisible parts problem only started to show up after connecting remotely and has never showed up while working on-stie. However, other softwares, like MATLAB, seem working properly with remote desktop, including all the plotting functions I have used so far.  

Am I getting this problem because of remote desktop microsoft due to some python packages/drivers used by Phy2 imcompatible with/don't support remote desktop?  Or is this a new problem that came up only recenly due to other reasons irrelevant to working remotely?

Any suggestions/fixes are deeply appreciated! Thanks!

**Comment by HunsonAbadeer1** [comment]
I tried both as well, with the unoffical PyOpenGL i have the problem that none of these versions is a supported wheel on the platform, probably since i am using version 2.7. Is there a usable version for me or do I rather upgrade phy?

**Comment by rossant** [comment]
Python 2.7 is unsupported, you should use a Python 3.6+ environment

**Comment by HunsonAbadeer1** [comment]
I changed to 3.8.2 and know was ablto follow chourans advise, but that did not change anything. The result is still identical.

**Comment by chouran** [comment]
I think the issue might come from vispy directly, I also have this [issue](https://github.com/vispy/vispy/issues/1342)

**Comment by rossant** [comment]
In case that's useful, phy is working correctly on my Windows 10 machine with the following versions:

```
Python 3.7.3

PyOpenGL                           3.1.0
PyQt5                              5.12.1
PyQt5-sip                          4.19.15
PyQtWebEngine                      5.12.1
```

**Comment by chouran** [comment]
Thank you @rossant, i'll try to downgrade my packages. Do you have a dedicated or integrated GPU ? One of the vispy developers pointed that integrated Intel GPU might be the core of the problem

**Comment by rossant** [comment]
@chouran absolutely, Intel GPUs cause some problems. But a recent Intel graphics driver seems to have fixed it : https://github.com/cortex-lab/phy/issues/957#issuecomment-609498355
I have an nvidia GPU on my Windows machine, this is the recommended graphics configuration for phy.

**Comment by HunsonAbadeer1** [comment]
I tried with the versions that worked for rossant and than with rossants versions and the PyOpenGl Package recommended by chouran, both still had the same result as in the beginning. Did anyone else that had the same problem encounter a solution by now?

**Comment by chouran** [comment]
Same for me. I’ve tried every possible combinations of package versions, same results, whatever the installation chosen. The Vispy library also fails to work. The intel drivers for some types of old integrated graphic card are most likely the core of the problem. The one I have is an Intel Graphics 3000 updated and supporting OpenGL 3.1, however it is no longer patched since 2015.

I’ve tried with a more recent computer, with an Intel graphics 4400, and everything works fine, both phy and vispy ..

**Comment by HunsonAbadeer1** [comment]
I was able to use the Phy GUI on the same Dataset with just the very basic manual from GitHub and no fancy packages on another computer. I think the problem was definetly the  NVIDIA GeForce RTX 2080 Ti, I used an Intel(R) UHD Graphics 630 and it worked on the first try.
